/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.erpinterfaceset.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.erpinterfaceset.core.entity.Material.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Tue Aug 06 12:04:33 CST 2024")
public class Material_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Material,String> auxunit;
    public static volatile SingularAttribute<Material,String> baseunit;
    public static volatile SingularAttribute<Material,String> erpMaterialHash;
    public static volatile SingularAttribute<Material,String> erpMaterialId;
    public static volatile SingularAttribute<Material,String> group;
    public static volatile SingularAttribute<Material,String> groupLarge;
    public static volatile SingularAttribute<Material,String> groupMedium;
    public static volatile SingularAttribute<Material,String> groupSmall;
    public static volatile SingularAttribute<Material,String> id;
    public static volatile SingularAttribute<Material,String> name;
    public static volatile SingularAttribute<Material,String> number;
    public static volatile SingularAttribute<Material,String> purchasepriceunit;
    public static volatile SingularAttribute<Material,String> purchaseunit;
    public static volatile SingularAttribute<Material,String> specification;
    public static volatile SingularAttribute<Material,String> ylahgkbum;
}
